# Generated by Django 4.2.7 on 2023-11-23 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Company_name", models.CharField(max_length=255)),
                ("company_address", models.TextField()),
                ("phone_number", models.CharField(max_length=15)),
                ("company_pan", models.CharField(max_length=100)),
                ("company_accountNo", models.BigIntegerField()),
                ("company_bankName", models.CharField(max_length=100)),
                ("company_bankifsc", models.CharField(max_length=100)),
                ("company_bankBranch", models.CharField(max_length=100)),
                ("company_accHolder", models.CharField(max_length=100)),
                ("gst_number", models.CharField(max_length=15)),
                ("fssai_number", models.CharField(max_length=15)),
                ("product_note", models.CharField(max_length=200)),
                ("invoice_number", models.CharField(max_length=20)),
                ("invoice_date", models.DateField()),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="company_logos/"
                    ),
                ),
                ("customer_name", models.CharField(max_length=255)),
                ("customer_address", models.TextField()),
                ("customer_mobile_number", models.CharField(max_length=15)),
                ("customer_email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=255)),
                ("mrp", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.PositiveIntegerField()),
                ("base_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("disc_1", models.DecimalField(decimal_places=2, max_digits=10)),
                ("disc_2", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "taxable_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("cgst_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("cgst_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("sgst_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("sgst_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "order_discount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("Credit_card", "Credit_card"),
                            ("Debit_card", "Debit_card"),
                            ("COD", "COD"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="Invoice_app.invoice",
                    ),
                ),
            ],
        ),
    ]
